//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabClientPermissionWithAgency
    {
        public int intAgencyPerId { get; set; }
        public int intPermissionId { get; set; }
        public int intAgencyId { get; set; }
        public bool bitIsUsed { get; set; }
    
        public virtual tabClientPermission tabClientPermission { get; set; }
    }
}
