//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabClientPermissionWithProduct
    {
        public int intProductClassificationPerId { get; set; }
        public int intPermissionId { get; set; }
        public int intProductId { get; set; }
        public bool bitIsKeywordSearch { get; set; }
        public bool bitIsWordSearch { get; set; }
        public bool bitIsExactPhrase { get; set; }
    
        public virtual tabClientPermission tabClientPermission { get; set; }
    }
}
