//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabClientDuration
    {
        public int intClientDurationId { get; set; }
        public int intClientId { get; set; }
        public System.DateTime dtStartDate { get; set; }
        public System.DateTime dtLastDate { get; set; }
        public int intNoOfDays { get; set; }
        public bool bitActive { get; set; }
        public int intEntryBy { get; set; }
        public System.DateTime dtEntryDate { get; set; }
    }
}
