//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabClientFavouriteTender
    {
        public int intFavTenderId { get; set; }
        public int intClientId { get; set; }
        public int intOurRefNo { get; set; }
        public int intTenderType { get; set; }
        public System.DateTime datEnterDate { get; set; }
    }
}
