//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabClientDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabClientDetail()
        {
            this.tabClientPermissions = new HashSet<tabClientPermission>();
        }
    
        public int intClientId { get; set; }
        public string strFName { get; set; }
        public string strLName { get; set; }
        public string strDesignation { get; set; }
        public string strCmpName { get; set; }
        public string strAboutUs { get; set; }
        public string strAddress { get; set; }
        public int intLocId { get; set; }
        public Nullable<int> intPinCode { get; set; }
        public string intMobileNo { get; set; }
        public string intPhoneNo { get; set; }
        public string strAdditionalContactNo { get; set; }
        public string strEmailId1 { get; set; }
        public string strEmailId2 { get; set; }
        public string strAdditionalEmailid { get; set; }
        public string strWebsite { get; set; }
        public string strInterestProducts { get; set; }
        public string strRemarks { get; set; }
        public int intClientPurpose { get; set; }
        public bool bitDc { get; set; }
        public bool bitSendSampleTender { get; set; }
        public Nullable<System.DateTime> dtSendSampleTender { get; set; }
        public bool bitSendSampleTenderRegular { get; set; }
        public bool bitSendPromotional { get; set; }
        public Nullable<System.DateTime> dtSendPromotional { get; set; }
        public int intLeadSourceId { get; set; }
        public int intSalesEmpId { get; set; }
        public Nullable<int> intClientStatusSalesId { get; set; }
        public Nullable<System.DateTime> dt_FCC_Date { get; set; }
        public int intCareEmpId { get; set; }
        public Nullable<int> intClientStatusCareId { get; set; }
        public Nullable<System.DateTime> dt_FUP_Date { get; set; }
        public int intActive { get; set; }
        public Nullable<System.DateTime> dtStartDate { get; set; }
        public Nullable<System.DateTime> dtLastDate { get; set; }
        public string strPassword { get; set; }
        public System.Guid uniUniqueNo { get; set; }
        public bool bitTenderService { get; set; }
        public bool bitSubcontractor { get; set; }
        public bool bitTenderAwarded { get; set; }
        public bool bitProject { get; set; }
        public bool bitEmailAlert { get; set; }
        public bool bitSmsAlert { get; set; }
        public int intMailFormat { get; set; }
        public bool bitInterestedForRenewal { get; set; }
        public bool bitDailyMailSend { get; set; }
        public int intCategory { get; set; }
        public bool bitCollectionApprove { get; set; }
        public Nullable<System.DateTime> dtLastLoginDate { get; set; }
        public bool bitLocked { get; set; }
        public int intEntryBy { get; set; }
        public System.DateTime dtEntryDate { get; set; }
        public Nullable<int> intUpdateBy { get; set; }
        public Nullable<System.DateTime> dtUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabClientPermission> tabClientPermissions { get; set; }
    }
}
