//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabClientEmailHistory
    {
        public int intClientEmailId { get; set; }
        public int intClientId { get; set; }
        public int intEmailFormType { get; set; }
        public System.DateTime dtEnterDate { get; set; }
        public string strSentEmailLayout { get; set; }
        public bool isEmailSent { get; set; }
        public Nullable<int> intEnterBy { get; set; }
        public string strFromMailId { get; set; }
        public string strCCMailID { get; set; }
        public string strToMailId { get; set; }
    }
}
