//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabEmpEmailId
    {
        public int intEmailId { get; set; }
        public int intEmpId { get; set; }
        public string strEmailId { get; set; }
        public string strPassword { get; set; }
        public string strSmtpName { get; set; }
        public Nullable<int> intSmtpPort { get; set; }
        public int intEntryBy { get; set; }
        public System.DateTime dtEntryDate { get; set; }
        public Nullable<int> intUpdateBy { get; set; }
        public Nullable<System.DateTime> dtUpdateDate { get; set; }
    
        public virtual tabEmpDetail tabEmpDetail { get; set; }
    }
}
