//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabEmpDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabEmpDetail()
        {
            this.tabEmpEmailIds = new HashSet<tabEmpEmailId>();
        }
    
        public int intEmpId { get; set; }
        public string strFname { get; set; }
        public string strLname { get; set; }
        public string intContactNo { get; set; }
        public string intCompContactNo { get; set; }
        public string strPassword { get; set; }
        public string strAddress { get; set; }
        public int intRoleId { get; set; }
        public bool bitActive { get; set; }
        public bool bitOnRole { get; set; }
        public bool bitCommitmentLock { get; set; }
        public bool bitLogin { get; set; }
        public Nullable<System.DateTime> dtLoginDate { get; set; }
        public Nullable<System.DateTime> dtLogoutDate { get; set; }
        public int intEntryBy { get; set; }
        public System.DateTime dtEntryDate { get; set; }
        public Nullable<int> intUpdateBy { get; set; }
        public Nullable<System.DateTime> dtUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabEmpEmailId> tabEmpEmailIds { get; set; }
    }
}
