//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAgencyIndian
    {
        public int AgencyId { get; set; }
        public string AgencyName { get; set; }
        public int SectorId { get; set; }
        public string SectorName { get; set; }
        public int OwnershipId { get; set; }
        public string OwnershipName { get; set; }
    
        public virtual tbOwnership tbOwnership { get; set; }
        public virtual tbSector tbSector { get; set; }
    }
}
