//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCountryRegionAssocation
    {
        public int Id { get; set; }
        public int CountryId { get; set; }
        public int RegionId { get; set; }
    
        public virtual tbCountry tbCountry { get; set; }
        public virtual tbRegion tbRegion { get; set; }
    }
}
