//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInquiryRegForm
    {
        public int ID { get; set; }
        public int InquiryTypeID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string CompName { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public string MobNo { get; set; }
        public string PhoneNo { get; set; }
        public string InterestedTenders { get; set; }
        public string Website { get; set; }
        public Nullable<int> intClientPurpose { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> OurRefNo { get; set; }
        public Nullable<int> NewID { get; set; }
        public int Flag { get; set; }
        public Nullable<int> ModuleType { get; set; }
        public Nullable<int> LinkId { get; set; }
        public string BrowserLink { get; set; }
        public string FormTitle { get; set; }
        public string ClientIPAddress { get; set; }
        public string ClientMACAddress { get; set; }
    }
}
