//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderDocFile
    {
        public int OurRefNo { get; set; }
        public string DocFilesNamePath { get; set; }
        public int EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
