//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderAssist.Models.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderClassified
    {
        public int OurRefNo { get; set; }
        public int ProductsId { get; set; }
        public int SubIndustryId { get; set; }
        public int IndustryId { get; set; }
    
        public virtual tbIndustry tbIndustry { get; set; }
        public virtual tbProduct tbProduct { get; set; }
        public virtual tbSubIndustry tbSubIndustry { get; set; }
    }
}
